;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programming source file
;; You should make any changes there and regenerate it from Emacs org-mode using C-c C-v t

;; Use a hook so the message doesn't get naenaed by the other messages
(add-hook 'emacs-startup-hook
          (lambda ()
                 (message "Emacs ready in %s with %d garbage collections."
                          (format "%.2f seconds"
                                  (float-time
                                   (time-subtract after-init-time before-init-time)))
                          gcs-done)))

(let ((file-name-handler-alist nil))

(setq debug-on-error nil)

(setq gc-cons-threshold most-positive-fixnum)

(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)

(require 'package)
(add-to-list 'package-archives (cons "melpa" "http://melpa.org/packages/"))
(add-to-list 'package-archives (cons "gnu" "http://elpa.gnu.org/packages/"))

(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

(when (not (package-installed-p 'use-package))
  (package-install 'use-package))

(require 'use-package)

(customize-set-variable 'use-package-always-ensure t)

(customize-set-variable 'use-package-always-defer t)

(customize-set-variable 'use-package-verbose nil)

(customize-set-variable 'load-prefer-newer t)
(use-package auto-compile
  :defer nil
  :config (auto-compile-on-load-mode))

(add-to-list 'load-path "~/.emacs.d/lisp")

(server-start)

(add-hook 'before-save-hook 'time-stamp)

(setq completion-ignore-case t)
(customize-set-variable 'read-file-name-completion-ignore-case t)
(customize-set-variable 'read-buffer-completion-ignore-case t)

(when (>= emacs-major-version 26)
  (use-package display-line-numbers))

(customize-set-variable 'show-trailing-whitespace nil)

(show-paren-mode)

(customize-set-variable 'indent-tabs-mode nil)

(customize-set-variable 'backup-directory-alist `(("." . ,(concat user-emacs-directory "backups"))))

(use-package saveplace
             :defer nil
             :config
             (save-place-mode))

(use-package smooth-scrolling
             :config
             (smooth-scrolling-mode 1))

(add-hook 'before-save-hook 'delete-trailing-whitespace)

(use-package org
             :bind
             
             :custom
             (org-directory "~/cs/org")
             (org-log-done t)
             (org-startup-indented t)
             (org-hide-emphasis-markers t)
             (org-tags-column 0)
             (org-todo-keyword-faces
              '(("TODO" . "red")
                ("[TODO]" . "red")
                ("DRAFT" . "yellow")
                ("[DRAFT]" . "yellow")
                ("DONE" . "green")
                ("[DONE]" . "green")
                ("CANCELED" . "blue")
                ("[CANCELED]" . "blue")))
             :custom-face
             (variable-pitch ((t (:family "Source Sans Pro" :height 160 :weight light))))
             (fixed-pitch ((t (:font "DejaVuSansMono Nerd Font" :height 1.0))))
             (org-indent ((t (:inherit (org-hide fixed-pitch)))))
             :hook
             (org-mode . visual-line-mode)
             (org-mode . variable-pitch-mode)
             :config
             (font-lock-add-keywords 'org-mode
                                     '(("^ *\\([-]\\) "
                                        (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
             (ojf/set-org-fonts)
             ;; (eval-after-load 'face-remap '(diminish 'buffer-face-mode))
             ;; (eval-after-load 'simple '(diminish 'visual-line-mode))
             )

(use-package org-indent
               :ensure nil
               :diminish
)

(defun org-get-keyboard (key)
  (org-element-map (org-element-parse-buffer 'element) 'keyboard
    (lambda (k)
      (when (string= key (org-element-property :key k))
        (org-element-property :value k)))
    nil t))

(use-package ox-reveal
  :load-path ("lisp/org-reveal")
  :defer 3
  :after org
  :custom
  (org-reveal-note-key-char nil)
  (org-reveal-root "file:///Users/taazadi1/Dropbox/org/reveal.js"))
(use-package htmlize
  :defer 3
  :after ox-reveal)

(use-package ox-md
             :ensure nil
             :defer 3
             :after org)

(use-package ox-gfm
             :defer 3
             :after org)

(use-package org-journal
  :after org
  :custom
  (org-journal-dir "~/cs/logbook"))

(use-package org-bullets
  :after org
  :hook
  (org-mode . (lambda () (org-bullets-mode 1))))

(defun ojf/set-org-fonts ()
    (let* ((variable-tuple
            (cond ((x-list-fonts   "Source Sans Pro") '(:font   "Source Sans Pro"))
                  ((x-list-fonts   "Lucida Grande")   '(:font   "Lucida Grande"))
                  ((x-list-fonts   "Verdana")         '(:font   "Verdana"))
                  ((x-family-fonts "Sans Serif")      '(:family "Sans Serif"))
                  (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
           (base-font-color (face-foreground 'default nil 'default))
           (headline       `(:inherit default :weight bold :foreground ,base-font-color)))

      (custom-theme-set-faces
       'user
       `(org-level-8        ((t (,@headline ,@variable-tuple))))
       `(org-level-7        ((t (,@headline ,@variable-tuple))))
       `(org-level-6        ((t (,@headline ,@variable-tuple))))
       `(org-level-5        ((t (,@headline ,@variable-tuple))))
       `(org-level-4        ((t (,@headline ,@variable-tuple :height 1.1))))
       `(org-level-3        ((t (,@headline ,@variable-tuple :height 1.25))))
       `(org-level-2        ((t (,@headline ,@variable-tuple :height 1.5))))
       `(org-level-1        ((t (,@headline ,@variable-tuple :height 1.75))))
       `(org-document-title ((t (,@headline ,@variable-tuple :height 2.0 :underline nil)))))))

(use-package toc-org
  :after org
  :hook
  (org-mode . toc-org-enable))

(defun ojf/org-reformat-buffer ()
  (interactive)
  (when (y-or-n-p "Really format current buffer? ")
    (let ((document (org-element-interpret-data (org-element-parse-buffer))))
      (erase-buffer)
      (insert document)
      (goto-char (point-min)))))

(use-package evil
  :defer .1
  :bind
  
  :init
  (setq evil-want-integration nil)
  (setq evil-want-keybinding nil)
  
  :config
  (evil-mode)
  )

(eval-after-load "evil"
  '(progn
     (define-key evil-normal-state-map (kbd "C-h") 'evil-window-left)
     (define-key evil-normal-state-map (kbd "C-j") 'evil-window-down)
     (define-key evil-normal-state-map (kbd "C-k") 'evil-window-up)
     (define-key evil-normal-state-map (kbd "C-l") 'evil-window-right)))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

(use-package evil-mc
  :hook (after-init . global-evil-mc-mode))

(use-package evil-org
  :after evil
  :defer .1
  :config
  (add-hook 'org-mode-hook 'evil-org-mode)
  (evil-org-set-key-theme '(navigation insert textobjects additional calendar)))

(add-hook 'eshell-mode-hook
          (lambda ()
            (remove-hook 'eshell-output-filter-functions
                         'eshell-postoutput-scroll-to-bottom)))

(defun eshell-clear-buffer ()
  "Clear terminal"
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (eshell-send-input)))

(add-hook 'eshell-mode-hook
      '(lambda()
          (local-set-key (kbd "SPC-b-c") 'eshell-clear-buffer)))

(add-hook 'prog-mode-hook #'display-line-numbers-mode)

(use-package rainbow-delimiters
  :commands rainbow-delimeters-mode
  :init
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))

(use-package magit)

(use-package git-gutter-fringe
  :hook (after-init . global-git-gutter-mode)
  :config
  (setq-default fringes-outside-margins t)
  (define-fringe-bitmap 'git-gutter-fr:added [224]
    nil nil '(center repeated))
  (define-fringe-bitmap 'git-gutter-fr:modified [224]
    nil nil '(center repeated))
  (define-fringe-bitmap 'git-gutter-fr:deleted [128 192 224 240]
    nil nil 'bottom))

(use-package projectile
  :config
  (projectile-mode 1)
  :hook (java-mode . projectile-mode))

(use-package yasnippet
  :diminish yas-minor-mode)

(use-package lsp-mode
  :init
  (setq lsp-prefer-flymake nil)
  :demand t)

(use-package lsp-java
  :hook ('java-mode . 'lsp))

(use-package lsp-ui
  :hook ('java-mode . 'flycheck-mode)
  :config
  (setq flycheck-indication-mode 'left-fringe)
  (define-fringe-bitmap 'flycheck-fringe-bitmap-double-arrow
    [16 48 112 240 112 48 16] nil nil 'center))

(setq lsp-ui-doc-enable nil
      lsp-ui-sideline-enable nil
      lsp-ui-flycheck-enable t)

(use-package dap-mode
  :diminish
  :defer .1
  :after (lsp-mode)
  :config
  (dap-mode t)
  (dap-ui-mode t))

(use-package dap-java
  :defer .1
  :after (lsp-java)
  :ensure nil)

(setq dap-java-java-command "gnome-terminal -- java")

(use-package gradle-mode
  :defer .1
  :diminish gradle-mode
  :config
  (add-hook 'java-mode-hook 'gradle-mode))

(use-package company
  :diminish company-mode
  :hook ('java-mode . 'company-mode)
  :config
  (setq company-dabbrev-downcase 0)
  (setq company-idle-delay 0.3)
  (setq company-minimum-prefix-length 2))

(use-package company-lsp
  :config
  (push 'company-lsp company-backends))

(use-package web-mode
  :config
  (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode)))

(defun ojf/open-init ()
  (interactive)
  (find-file "~/.emacs.d/init.org"))

(defun ojf/change-theme-light ()
  (interactive)
  (load-theme 'gruvbox-light-soft)
  (ojf/set-org-fonts)
  (powerline-reset))

(defun ojf/change-theme-dark ()
  (interactive)
  (load-theme 'gruvbox-dark-medium)
  (ojf/set-org-fonts)
  (powerline-reset))

(defun ojf/reload-emacs ()
  (interactive)
  (org-babel-tangle "~/.emacs.d/init.org")
  (load-file "~/.emacs.d/init.el"))

(defun ojf/dap-debug-last ()
  (interactive)
  (dap-debug-last)
  (let ((win-curr (selected-window))
        (win-other (next-window)))
    (select-window win-other)
    (delete-window)
    (select-window win-curr)))

(use-package general
  :defer .1
  :config
  (general-create-definer global-leader-def
                          :prefix "SPC")

  ;; global evil leader bindings
  (global-leader-def
   :states 'normal
   :keymaps 'override
   ;; Buffer ops
   "b s" 'save-buffer
   "b o" 'helm-find-files
   "b k" 'kill-current-buffer
   ;; Customization
   "c e e" 'ojf/open-init
   "c e r" 'ojf/reload-emacs
   "c t l" 'ojf/change-theme-light
   "c t d" 'ojf/change-theme-dark
   ;; Magit stuff
   "g g" 'magit-status
   "g i" 'magit-init
   )

  ;; mode bindings
  (general-create-definer mode-leader-def
    :prefix "SPC m")

  (mode-leader-def
    :states 'normal
    :keymaps 'java-mode-map
    "d l" 'dap-ui-locals
    "d r" 'dap-ui-repl
    "d n" 'dap-next
    "d b" 'dap-breakpoint-toggle
    "d c" 'dap-continue
    "d d" 'ojf/dap-debug-last
    ))

(use-package neotree
  :after evil
  :defer .1
  :config
  (global-set-key [f8] 'neotree-toggle)
  (setq neo-theme (if (display-graphic-p) 'icons 'arrow))
  (add-hook 'neotree-mode-hook
            (lambda ()
              (define-key evil-normal-state-local-map (kbd "TAB") 'neotree-enter)
              (define-key evil-normal-state-local-map (kbd "SPC") 'neotree-quick-look)
              (define-key evil-normal-state-local-map (kbd "q") 'neotree-hide)
              (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter)
              (define-key evil-normal-state-local-map (kbd "g") 'neotree-refresh)
              (define-key evil-normal-state-local-map (kbd "n") 'neotree-next-line)
              (define-key evil-normal-state-local-map (kbd "p") 'neotree-previous-line)
              (define-key evil-normal-state-local-map (kbd "A") 'neotree-stretch-toggle)
              (define-key evil-normal-state-local-map (kbd "H") 'neotree-hidden-file-toggle)))
  )

(use-package plantuml-mode
  :config
  (setq plantuml-jar-path "~/.config/plantuml/plantuml.jar")
  (setq plantuml-default-exec-mode 'jar)
  (add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode)))

(electric-pair-mode 1)

(use-package diminish
  :defer 1)

(use-package doom-modeline
  :hook (after-init . doom-modeline-mode))

(use-package doom-themes)
(use-package gruvbox-theme)
(load-theme 'gruvbox-dark-medium)

(add-to-list 'default-frame-alist
             '(font . "DejaVuSansMono Nerd Font-12:style=Book"))

(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)

(use-package uniquify
  :defer 1
  :ensure nil
  :custom
  (uniquify-after-kill-buffer-p t)
  (uniquify-buffer-name-style 'post-forward)
  (uniquify-strip-common-suffix t))

(use-package midnight
  :defer 3
  :config
  (setq midnight-period 7200)
  (midnight-mode 1))

(use-package all-the-icons
  :config
  (when (not (member "all-the-icons" (font-family-list)))
    (all-the-icons-install-fonts t)))

(use-package helm
  :ensure t
  :diminish helm-mode
  :bind
  ("C-x C-f" . 'helm-find-files)
  ("C-x C-b" . 'helm-buffers-list)
  ("M-x" . 'helm-M-x)
  :config
  (defun daedreth/helm-hide-minibuffer ()
    (when (with-helm-buffer helm-echo-input-in-header-line)
      (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
        (overlay-put ov 'window (selected-window))
        (overlay-put ov 'face
                     (let ((bg-color (face-background 'default nil)))
                       `(:background ,bg-color :foreground ,bg-color)))
        (setq-local cursor-type nil))))
  (add-hook 'helm-minibuffer-set-up-hook 'daedreth/helm-hide-minibuffer)
  (setq helm-autoresize-max-height 0
        helm-autoresize-min-height 40
        helm-M-x-fuzzy-match t
        helm-buffers-fuzzy-matching t
        helm-recentf-fuzzy-match t
        helm-semantic-fuzzy-match t
        helm-imenu-fuzzy-match t
        helm-split-window-in-side-p nil
        helm-move-to-line-cycle-in-source nil
        helm-ff-search-library-in-sexp t
        helm-scroll-amount 8
        helm-echo-input-in-header-line t)
  :init
  (helm-mode 1))

(require 'helm-config)
(helm-autoresize-mode 1)
(define-key helm-find-files-map (kbd "C-b") 'helm-find-files-up-one-level)
(define-key helm-find-files-map (kbd "C-f") 'helm-execute-persistent-action)

)

(setq gc-cons-threshold (* 2 1000 1000))
